- name: docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t petstore .
      args:
        chdir: /var/lib/jenkins/workspace/petstore

    - name: tag image
<<<<<<< HEAD
      command: docker tag petstore:latest sevenajay/petstore:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: dockerhub username
        password: dockerhub password/PAT

    - name: Push image
      command: docker push sevenajay/petstore:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 sevenajay/petstore:latest
=======
      command: docker tag petshop:latest sravani0508/petshop:tagname 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        # registry_url: https://hub.docker.com/repositories/sravani0508
        registry_url: https://hub.docker.com/repository/docker/sravani0508/petshop
        username: sravani0508
        password: Family@1305

    - name: Push image
      command: docker push sravani0508/petshop:tagname

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 sravani0508/petshop:tagname
>>>>>>> 069cb7a2cd29d8b160fbb53eddd05c723d0af013
